name: React CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone project
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v4.1.0

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy
      run: echo "Project deployed successfully" 
