name: React CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Clone Project
      uses: actions/checkout@v3

    - name: Installing Node.js
      uses: actions/setup-node@v4.1.0

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      run: echo "Project deployed successfully"

