name: React CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Installing Node.js
      uses: actions/setup-node@v21.6.2

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 5: Build the project
    - name: Build
      run: npm run build

    - name: Deploy
      run: echo "Project deployed successfully"

